if State.count == 0
  State.create(ibge_code: '12', uf: 'AC', name: 'Acre', country: Country.first)
  State.create(ibge_code: '27', uf: 'AL', name: 'Alagoas', country: Country.first)
  State.create(ibge_code: '13', uf: 'AM', name: 'Amazonas', country: Country.first)
  State.create(ibge_code: '16', uf: 'AP', name: 'Amapá', country: Country.first)
  State.create(ibge_code: '29', uf: 'BA', name: 'Bahia', country: Country.first)
  State.create(ibge_code: '23', uf: 'CE', name: 'Ceará', country: Country.first)
  State.create(ibge_code: '53', uf: 'DF', name: 'Distrito Federal', country: Country.first)
  State.create(ibge_code: '32', uf: 'ES', name: 'Espírito Santo', country: Country.first)
  State.create(ibge_code: '52', uf: 'GO', name: 'Goiás', country: Country.first)
  State.create(ibge_code: '21', uf: 'MA', name: 'Maranhão', country: Country.first)
  State.create(ibge_code: '31', uf: 'MG', name: 'Minas Gerais', country: Country.first)
  State.create(ibge_code: '50', uf: 'MS', name: 'Mato Grosso do Sul', country: Country.first)
  State.create(ibge_code: '51', uf: 'MT', name: 'Mato Grosso', country: Country.first)
  State.create(ibge_code: '15', uf: 'PA', name: 'Pará', country: Country.first)
  State.create(ibge_code: '25', uf: 'PB', name: 'Paraíba', country: Country.first)
  State.create(ibge_code: '26', uf: 'PE', name: 'Pernambuco', country: Country.first)
  State.create(ibge_code: '22', uf: 'PI', name: 'Piauí', country: Country.first)
  State.create(ibge_code: '41', uf: 'PR', name: 'Paraná', country: Country.first)
  State.create(ibge_code: '33', uf: 'RJ', name: 'Rio de Janeiro', country: Country.first)
  State.create(ibge_code: '24', uf: 'RN', name: 'Rio Grande do Norte', country: Country.first)
  State.create(ibge_code: '11', uf: 'RO', name: 'Rondônia', country: Country.first)
  State.create(ibge_code: '14', uf: 'RR', name: 'Roraima', country: Country.first)
  State.create(ibge_code: '43', uf: 'RS', name: 'Rio Grande do Sul', country: Country.first)
  State.create(ibge_code: '42', uf: 'SC', name: 'Santa Catarina', country: Country.first)
  State.create(ibge_code: '28', uf: 'SE', name: 'Sergipe', country: Country.first)
  State.create(ibge_code: '35', uf: 'SP', name: 'São Paulo', country: Country.first)
  State.create(ibge_code: '17', uf: 'TO', name: 'Tocantis', country: Country.first)
end
